// Code generated by sysgo; DO NOT EDIT.

package domain

// InstallRequest is a value object: immutable and compared by value.
type InstallRequest struct {
	ReleaseName string `json:"releaseName"`
	SkillID     string `json:"skillId"`
	Target      Target `json:"target"`
	Namespace   string `json:"namespace"`
	Values      string `json:"values"`
}

// Equal reports whether two InstallRequest values are equal.
func (i InstallRequest) Equal(other InstallRequest) bool {
	return i == other
}
