// Code generated by sysgo; DO NOT EDIT.

package domain

// LockPin is a value object: immutable and compared by value.
type LockPin struct {
	Ref    string `json:"ref"`
	Digest string `json:"digest"`
	Tag    string `json:"tag"`
}

// Equal reports whether two LockPin values are equal.
func (l LockPin) Equal(other LockPin) bool {
	return l == other
}
