// Code generated by sysgo; DO NOT EDIT.

package domain

// NewLockfile is a factory that constructs a valid Lockfile aggregate.
// Add invariant checks here; return an error when they are violated.
func NewLockfile() (*Lockfile, error) {
	return &Lockfile{}, nil
}
