// Code generated by sysgo; DO NOT EDIT.

package domain

// Lockfile is an aggregate root. It is the consistency boundary for its
// contained entities and value objects; mutate it only through its methods.
type Lockfile struct {
	ID      string     `json:"id"`
	Pins    []LockPin  `json:"pins"`
	History []Revision `json:"history"`
}
