// Code generated by sysgo; DO NOT EDIT.

package domain

// NewRelease is a factory that constructs a valid Release aggregate.
// Add invariant checks here; return an error when they are violated.
func NewRelease() (*Release, error) {
	return &Release{}, nil
}
