// Code generated by sysgo; DO NOT EDIT.

package domain

// Release is an aggregate root. It is the consistency boundary for its
// contained entities and value objects; mutate it only through its methods.
type Release struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Target    Target     `json:"target"`
	Namespace string     `json:"namespace"`
	Revisions []Revision `json:"revisions"`
}
