// Code generated by sysgo; DO NOT EDIT.

package domain

// Revision is a value object: immutable and compared by value.
type Revision struct {
	Number  int64     `json:"number"`
	Version string    `json:"version"`
	Values  string    `json:"values"`
	Pins    []LockPin `json:"pins"`
	Blob    string    `json:"blob"`
}
