// Code generated by sysgo; DO NOT EDIT.

package domain

// RollbackRequest is a value object: immutable and compared by value.
type RollbackRequest struct {
	ReleaseName string `json:"releaseName"`
	ToRevision  int64  `json:"toRevision"`
}

// Equal reports whether two RollbackRequest values are equal.
func (r RollbackRequest) Equal(other RollbackRequest) bool {
	return r == other
}
