// Code generated by sysgo; DO NOT EDIT.

package domain

// Target is a value object: immutable and compared by value.
type Target struct {
	Value string `json:"value"`
}

// Equal reports whether two Target values are equal.
func (t Target) Equal(other Target) bool {
	return t == other
}
