// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/stats/domain"
)

// ReadStatisticsInput is the input DTO for the ReadStatistics use case.
type ReadStatisticsInput struct {
	Skill string `json:"skill"`
}

// ReadStatisticsOutput is the output DTO for the ReadStatistics use case.
type ReadStatisticsOutput struct {
	Snapshot domain.CountSnapshot `json:"snapshot"`
}

// ReadStatisticsUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type ReadStatisticsUseCase interface {
	ReadStatistics(input ReadStatisticsInput) (ReadStatisticsOutput, error)
}
