// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/stats/domain"
)

// RecordPullInput is the input DTO for the RecordPull use case.
type RecordPullInput struct {
	Request domain.CountRequest `json:"request"`
}

// RecordPullOutput is the output DTO for the RecordPull use case.
type RecordPullOutput struct {
	Snapshot domain.CountSnapshot `json:"snapshot"`
}

// RecordPullUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type RecordPullUseCase interface {
	RecordPull(input RecordPullInput) (RecordPullOutput, error)
}
