// Code generated by sysgo; DO NOT EDIT.

package domain

// Signature is a value object: immutable and compared by value.
type Signature struct {
	ReferrerDigest string `json:"referrerDigest"`
	Payload        string `json:"payload"`
}

// Equal reports whether two Signature values are equal.
func (s Signature) Equal(other Signature) bool {
	return s == other
}
