// Code generated by sysgo; DO NOT EDIT.

package domain

// VerifyPolicy is a value object: immutable and compared by value.
type VerifyPolicy struct {
	RequireSignature bool `json:"requireSignature"`
}

// Equal reports whether two VerifyPolicy values are equal.
func (v VerifyPolicy) Equal(other VerifyPolicy) bool {
	return v == other
}
