// Code generated by sysgo; DO NOT EDIT.

package domain

// NewVerificationSubject is a factory that constructs a valid VerificationSubject aggregate.
// Add invariant checks here; return an error when they are violated.
func NewVerificationSubject() (*VerificationSubject, error) {
	return &VerificationSubject{}, nil
}
