// Code generated by sysgo; DO NOT EDIT.

package domain

// VerificationSubject is an aggregate root. It is the consistency boundary for its
// contained entities and value objects; mutate it only through its methods.
type VerificationSubject struct {
	ID         string      `json:"id"`
	Digest     string      `json:"digest"`
	Signatures []Signature `json:"signatures"`
}
