// Code generated by sysgo; DO NOT EDIT.

package domain

// VerifyRequest is a value object: immutable and compared by value.
type VerifyRequest struct {
	SubjectDigest string       `json:"subjectDigest"`
	Policy        VerifyPolicy `json:"policy"`
}

// Equal reports whether two VerifyRequest values are equal.
func (v VerifyRequest) Equal(other VerifyRequest) bool {
	return v == other
}
