// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/install/domain"
)

// InstallSkillInput is the input DTO for the InstallSkill use case.
type InstallSkillInput struct {
	Request domain.InstallRequest `json:"request"`
}

// InstallSkillOutput is the output DTO for the InstallSkill use case.
type InstallSkillOutput struct {
	Result domain.InstallResult `json:"result"`
}

// InstallSkillUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type InstallSkillUseCase interface {
	InstallSkill(input InstallSkillInput) (InstallSkillOutput, error)
}
