// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/install/domain"
)

// ReadHistoryInput is the input DTO for the ReadHistory use case.
type ReadHistoryInput struct {
	ReleaseName string `json:"releaseName"`
}

// ReadHistoryOutput is the output DTO for the ReadHistory use case.
type ReadHistoryOutput struct {
	Result domain.InstallResult `json:"result"`
}

// ReadHistoryUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type ReadHistoryUseCase interface {
	ReadHistory(input ReadHistoryInput) (ReadHistoryOutput, error)
}
