// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/install/domain"
)

// RollbackSkillInput is the input DTO for the RollbackSkill use case.
type RollbackSkillInput struct {
	Request domain.RollbackRequest `json:"request"`
}

// RollbackSkillOutput is the output DTO for the RollbackSkill use case.
type RollbackSkillOutput struct {
	Result domain.InstallResult `json:"result"`
}

// RollbackSkillUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type RollbackSkillUseCase interface {
	RollbackSkill(input RollbackSkillInput) (RollbackSkillOutput, error)
}
