// Code generated by sysgo; DO NOT EDIT.

package in

// UninstallSkillInput is the input DTO for the UninstallSkill use case.
type UninstallSkillInput struct {
	ReleaseName string `json:"releaseName"`
}

// UninstallSkillOutput is the output DTO for the UninstallSkill use case.
type UninstallSkillOutput struct {
	Ok bool `json:"ok"`
}

// UninstallSkillUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type UninstallSkillUseCase interface {
	UninstallSkill(input UninstallSkillInput) (UninstallSkillOutput, error)
}
