// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/install/domain"
)

// UpgradeSkillInput is the input DTO for the UpgradeSkill use case.
type UpgradeSkillInput struct {
	Request domain.InstallRequest `json:"request"`
}

// UpgradeSkillOutput is the output DTO for the UpgradeSkill use case.
type UpgradeSkillOutput struct {
	Result domain.InstallResult `json:"result"`
}

// UpgradeSkillUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type UpgradeSkillUseCase interface {
	UpgradeSkill(input UpgradeSkillInput) (UpgradeSkillOutput, error)
}
