// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/registry/domain"
)

// DetectDiscoveryInput is the input DTO for the DetectDiscovery use case.
type DetectDiscoveryInput struct {
	Entry domain.RegistryEntry `json:"entry"`
}

// DetectDiscoveryOutput is the output DTO for the DetectDiscovery use case.
type DetectDiscoveryOutput struct {
	Result domain.CatalogResult `json:"result"`
}

// DetectDiscoveryUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type DetectDiscoveryUseCase interface {
	DetectDiscovery(input DetectDiscoveryInput) (DetectDiscoveryOutput, error)
}
