// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/registry/domain"
)

// ListSkillsInput is the input DTO for the ListSkills use case.
type ListSkillsInput struct {
	Secret domain.ListingSecret `json:"secret"`
}

// ListSkillsOutput is the output DTO for the ListSkills use case.
type ListSkillsOutput struct {
	Result domain.CatalogResult `json:"result"`
}

// ListSkillsUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type ListSkillsUseCase interface {
	ListSkills(input ListSkillsInput) (ListSkillsOutput, error)
}
