// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/registry/domain"
)

// ProxyManifestInput is the input DTO for the ProxyManifest use case.
type ProxyManifestInput struct {
	Request domain.ProxyRequest `json:"request"`
}

// ProxyManifestOutput is the output DTO for the ProxyManifest use case.
type ProxyManifestOutput struct {
	Response domain.ProxyResponse `json:"response"`
}

// ProxyManifestUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type ProxyManifestUseCase interface {
	ProxyManifest(input ProxyManifestInput) (ProxyManifestOutput, error)
}
