// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/registry/domain"
)

// RegisterRegistryInput is the input DTO for the RegisterRegistry use case.
type RegisterRegistryInput struct {
	Entry domain.RegistryEntry `json:"entry"`
}

// RegisterRegistryOutput is the output DTO for the RegisterRegistry use case.
type RegisterRegistryOutput struct {
	Ok bool `json:"ok"`
}

// RegisterRegistryUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type RegisterRegistryUseCase interface {
	RegisterRegistry(input RegisterRegistryInput) (RegisterRegistryOutput, error)
}
