package main

import (
	"slices"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/gaarutyunov/epos/internal/cli"
	"github.com/gaarutyunov/epos/internal/store"
)

// cliBanner is the banner the page carries, so nobody edits the output.
const cliBanner = "// Generated by `go run ./internal/docsgen` from the cobra command tree in\n" +
	"// internal/cli (SPEC.md 14.1). Do not edit by hand: CI regenerates this page\n" +
	"// and fails if the result differs. To change what it says, change the\n" +
	"// command's Short, Long or flag usage — the text below is the CLI's own help.\n"

// docsVersion is only here because cobra adds --version to a command whose
// Version is set, and a flag the CLI has is a flag the reference documents.
// The page never prints a version number, so which string this is does not
// reach the output.
const docsVersion = "0.0.0"

// renderCLI builds the CLI reference from the command definitions themselves.
//
// Nothing about the command surface is retyped here: the names, the usage
// lines, the summaries, the prose and every flag with its type and default come
// out of the same cobra tree cmd/epos executes, which is what SPEC.md 14.1
// means by "generated from the same source as the CLI's own help output". A
// command added to internal/cli appears on this page with no edit here, and the
// drift check fails until the page is regenerated.
func renderCLI() []byte {
	commands := walk(root())
	p := &page{}

	p.frontmatter(cliBanner)
	p.cliHeader(commands)
	p.cliContents(commands)
	p.environment()
	for _, cmd := range commands {
		p.command(cmd)
	}
	p.publishing()
	p.footer()
	p.cliStyles()

	return []byte(p.b.String())
}

// root is the command tree the page documents.
func root() *cobra.Command {
	cmd := cli.NewRootCommand(docsVersion)
	// Added during Execute in the real CLI, so a tree that was only built has
	// neither. --version is the root's alone; -h is on every command, which
	// walk sees to below.
	cmd.InitDefaultHelpFlag()
	cmd.InitDefaultVersionFlag()
	return cmd
}

// walk flattens the tree, depth first, parents before their children.
func walk(cmd *cobra.Command) []*cobra.Command {
	// What `epos <cmd> --help` prints, so what the page has to list.
	cmd.InitDefaultHelpFlag()

	out := []*cobra.Command{cmd}
	for _, child := range children(cmd) {
		out = append(out, walk(child)...)
	}
	return out
}

// children is a command's documented subcommands, in a fixed order.
//
// Sorted explicitly rather than trusting cobra's own ordering:
// EnableCommandSorting is a package-level variable any import could flip, and a
// page whose section order depended on that would be a drift check that fails
// for reasons nobody can see in the diff.
func children(cmd *cobra.Command) []*cobra.Command {
	out := slices.Clone(cmd.Commands())
	out = slices.DeleteFunc(out, func(child *cobra.Command) bool {
		// `help` and `completion` are cobra's, not the CLI's, and a hidden
		// command is hidden from `--help` too.
		return child.Hidden || child.IsAdditionalHelpTopicCommand() ||
			child.Name() == "help" || child.Name() == "completion"
	})
	slices.SortFunc(out, func(a, b *cobra.Command) int {
		return strings.Compare(a.Name(), b.Name())
	})
	return out
}

// anchor is a command's id on the page.
//
// Built from the whole path, because two different commands share a name:
// `epos ls` lists what a worktree pinned and `epos store ls` lists what the
// store holds.
func anchor(cmd *cobra.Command) string {
	return strings.ReplaceAll(cmd.CommandPath(), " ", "-")
}

func (p *page) cliHeader(commands []*cobra.Command) {
	p.w(
		`<Base`,
		`  title="CLI reference — Epos"`,
		`  description="`+escape(cliDescription(commands))+`"`,
		`>`,
		`  <p class="back"><a href={href("")}>← Epos</a></p>`,
		"",
		`  <header class="hero">`,
		`    <ga-badge color="blue">Reference</ga-badge>`,
		`    <h1>CLI reference</h1>`,
		`    <p class="lede">`,
		`      Every <code>epos</code> command and every flag it takes. This page is`,
		`      generated from the command definitions themselves, so it is the same`,
		`      text <code>epos --help</code> prints.`,
		`    </p>`,
		`    <p>`,
		`      New to Epos? The <a href={href("quickstart")}>quick start</a> runs the`,
		`      whole round trip end to end. For the composition language`,
		`      <code>epos build</code> evaluates, see the`,
		`      <a href={href("skillfile")}>Skillfile reference</a>.`,
		`    </p>`,
		`  </header>`,
		"",
	)
}

// cliDescription is the page's meta description.
//
// The command list in it is built from the tree rather than written out: a
// hard-coded one is exactly the sentence that still says `push` a year after
// the write path was withdrawn.
func cliDescription(commands []*cobra.Command) string {
	var names []string
	for _, cmd := range commands {
		if cmd.Parent() != nil && cmd.Parent().Parent() == nil {
			names = append(names, cmd.Name())
		}
	}
	return "Every epos command and flag — " + strings.Join(names, ", ") +
		" — with its usage, its options and their defaults. Generated from the CLI's own command definitions."
}

// cliContents is the in-page index.
func (p *page) cliContents(commands []*cobra.Command) {
	p.w(`  <nav class="toc" aria-label="On this page">`, `    <ul>`)
	p.w(`      <li><a href="#environment">Environment</a></li>`)
	for _, cmd := range commands {
		p.w(`      <li><a href="#` + anchor(cmd) + `"><code>` +
			escape(cmd.CommandPath()) + `</code></a></li>`)
	}
	p.w(`      <li><a href="#publishing">Publishing</a></li>`)
	p.w(`    </ul>`, `  </nav>`, "")
}

// environment documents what epos reads out of the environment.
//
// EPOS_HOME is not a flag, so nothing in the command tree mentions it and a
// walk of that tree alone would leave the one setting that decides where every
// byte of state lands undocumented. The name comes from the constant the
// resolution actually reads, so renaming the variable renames it here.
func (p *page) environment() {
	p.w(
		`  <section id="environment">`,
		`    <h2>Environment</h2>`,
		`    <p>`,
		`      Epos keeps its state — the local store above all — under one root`,
		`      directory. The root resolves in this order, first match winning:`,
		`    </p>`,
		`    <ol>`,
		`      <li>a directory an embedding program names outright; the CLI has no flag for this</li>`,
		`      <li><code>$`+escape(store.RootEnv)+`</code></li>`,
		`      <li><code>&lt;home&gt;/.epos</code>, the default</li>`,
		`    </ol>`,
		`    <p>`,
		`      Set <code>`+escape(store.RootEnv)+`</code> to keep epos state somewhere other than`,
		`      your home directory — a throwaway directory for an experiment, or a`,
		`      shared cache. It must be on a local filesystem: the store's advisory`,
		`      locks are unreliable over NFS and SMB.`,
		`    </p>`,
		`    <ga-code prompt="$">`+escape(store.RootEnv)+`=/tmp/epos epos store path</ga-code>`,
		`    <p>`,
		`      <a href="#epos-store-path"><code>epos store path</code></a> prints the`,
		`      directory that resolution arrived at, which is the quickest way to see`,
		`      whether the variable took effect.`,
		`    </p>`,
		`  </section>`,
		"",
	)
}

// command renders one command: its usage line, its summary, its own prose and
// its flags.
func (p *page) command(cmd *cobra.Command) {
	p.w(
		`  <section id="`+anchor(cmd)+`">`,
		`    <h2><code>`+escape(cmd.CommandPath())+`</code></h2>`,
		`    <pre class="syntax">`+escape(cmd.UseLine())+`</pre>`,
		`    <p class="summary">`+escape(cmd.Short)+`</p>`,
	)

	for _, para := range paragraphs(cmd.Long) {
		p.w(`    <p>` + escape(para) + `</p>`)
	}

	p.flags(cmd)
	p.subcommands(cmd)

	p.w(`  </section>`, "")
}

// flags renders the command's own flags, the way its help output lists them.
//
// LocalFlags leaves out what a parent declared, so nothing is documented twice,
// and the entries are sorted by name rather than taken in the order pflag hands
// them over.
func (p *page) flags(cmd *cobra.Command) {
	var flags []*pflag.Flag
	cmd.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if !f.Hidden {
			flags = append(flags, f)
		}
	})
	if len(flags) == 0 {
		return
	}
	slices.SortFunc(flags, func(a, b *pflag.Flag) int { return strings.Compare(a.Name, b.Name) })

	p.w(`    <dl class="flags">`)
	for _, f := range flags {
		term, usage := flagEntry(f)
		p.w(
			`      <dt><code>`+escape(term)+`</code></dt>`,
			`      <dd>`+escape(usage)+`</dd>`,
		)
	}
	p.w(`    </dl>`)
}

// subcommands links a parent to its children.
func (p *page) subcommands(cmd *cobra.Command) {
	kids := children(cmd)
	if len(kids) == 0 {
		return
	}

	links := make([]string, 0, len(kids))
	for _, child := range kids {
		links = append(links, `<a href="#`+anchor(child)+`"><code>`+
			escape(child.CommandPath())+`</code></a>`)
	}
	p.w(`    <p class="subcommands">Subcommands: ` + strings.Join(links, ", ") + `</p>`)
}

// publishing ties together the commands that make up one publish, which no
// single command's own help can do.
//
// It names them explicitly — see publishingCommands, and the test that holds
// this prose to it. `cliDescription`'s comment warns about "the sentence that
// still says push a year after the write path was withdrawn"; this block was
// that sentence's mirror image, asserting for months that a push does not exist
// because the *`epos-registry`* write path was withdrawn (SPEC.md 4.5). The
// drift gate regenerates commands from the cobra tree and so catches a missing
// command, but prose is invisible to it. Anything claimed here must be a claim
// about a command in publishingCommands.
func (p *page) publishing() {
	p.w(
		`  <section id="publishing">`,
		`    <h2>Publishing</h2>`,
		`    <p>`,
		`      <a href="#epos-push"><code>epos push</code></a> copies a packed or built`,
		`      skill from the local store to a registry. It is a direct`,
		`      client-to-registry copy of bytes that already exist: nothing is repacked`,
		`      and no digest is re-derived, so what lands upstream is what`,
		`      <a href="#epos-pack"><code>epos pack</code></a> printed.`,
		`    </p>`,
		`    <p>`,
		`      For a registry that wants a credential, run`,
		`      <a href="#epos-registry-login"><code>epos registry login</code></a>`,
		`      first; <a href="#epos-registry-logout"><code>epos registry logout</code></a>`,
		`      discards it. Both use the Docker credential store, so a credential a`,
		`      <code>docker login</code> already placed there is found without being`,
		`      copied.`,
		`    </p>`,
		`    <p>`,
		`      Publishing <em>through</em> <code>epos-registry</code> is a separate`,
		`      matter and stays withdrawn (SPEC.md 4.5): it would have to redirect the`,
		`      upload session to the registry behind it, and oras-go refuses a`,
		`      cross-host upload location. A client pointed straight at your registry`,
		`      gets that registry's own location and is unaffected, which is what`,
		`      <code>epos push</code> is.`,
		`    </p>`,
		`    <p>`,
		`      What epos produces is an ordinary OCI artifact in an OCI layout, so any`,
		`      other OCI client publishes it too — the`,
		`      <a href={href("quickstart")}>quick start</a> shows`,
		`      <code>oras cp</code> reading straight out of the directory`,
		`      <a href="#epos-store-path"><code>epos store path</code></a> prints.`,
		`    </p>`,
		`  </section>`,
		"",
	)
}

// publishingCommands is the set of commands the publishing block claims exist.
//
// It is the seam that makes that prose testable: TestPublishingNamesRealCommands
// asserts every entry is a real command in the cobra tree *and* that the
// rendered block links to it. A command that disappears, or prose that drifts
// off the commands, fails there rather than a year later in a bug report.
var publishingCommands = []string{
	"epos push",
	"epos pack",
	"epos registry login",
	"epos registry logout",
	"epos store path",
}

// paragraphs splits a cobra Long into paragraphs.
//
// Long is written for a terminal, so it is hard-wrapped: the line breaks inside
// a paragraph are the author's column limit, not meaning, and rendering them as
// breaks in HTML would reflow badly at every width. A blank line is the only
// break that means anything.
func paragraphs(long string) []string {
	var out []string
	for _, para := range strings.Split(strings.TrimSpace(long), "\n\n") {
		para = strings.TrimSpace(strings.ReplaceAll(para, "\n", " "))
		if para != "" {
			out = append(out, para)
		}
	}
	return out
}

// flagEntry renders one flag the way `--help` prints it: the shorthand, the
// name, the type it takes and its default.
func flagEntry(f *pflag.Flag) (term, usage string) {
	// pflag's own splitter, so the type shown is the type its help shows —
	// nothing for a bool, "stringArray" for a repeatable string, and so on.
	typeName, usage := pflag.UnquoteUsage(f)

	term = "--" + f.Name
	if f.Shorthand != "" {
		term = "-" + f.Shorthand + ", " + term
	}
	if typeName != "" {
		term += " " + typeName
	}

	if !defaultIsZero(f) {
		if f.Value.Type() == "string" {
			usage += ` (default "` + f.DefValue + `")`
		} else {
			usage += " (default " + f.DefValue + ")"
		}
	}
	return term, usage
}

// defaultIsZero reports whether a flag's default is the zero value, which
// `--help` leaves unprinted rather than showing as `(default "")`.
//
// pflag decides this by type-switching on its own unexported value types, so it
// cannot be called from here; this switches on the type name those values
// report instead, which is the same information by another route.
func defaultIsZero(f *pflag.Flag) bool {
	switch f.Value.Type() {
	case "bool":
		return f.DefValue == "false"
	case "duration":
		return f.DefValue == "0" || f.DefValue == "0s"
	case "string":
		return f.DefValue == ""
	default:
		switch f.DefValue {
		case "", "0", "false", "[]", "<nil>":
			return true
		}
		return false
	}
}

// cliStyles is the page's scoped CSS.
//
// Written out rather than escaped: a <style> element is raw text to Astro, so
// the braces here are CSS braces and must stay braces.
func (p *page) cliStyles() {
	p.w(
		"<style>",
		"  .back {",
		"    font-size: 0.9rem;",
		"    margin: 0 0 2rem;",
		"  }",
		"",
		"  .hero {",
		"    margin-bottom: 2.5rem;",
		"  }",
		"",
		"  h1 {",
		"    font-size: clamp(1.9rem, 5vw, 2.6rem);",
		"    line-height: 1.15;",
		"    letter-spacing: -0.02em;",
		"    margin: 1rem 0 0.75rem;",
		"  }",
		"",
		"  .lede {",
		"    font-size: 1.1rem;",
		"    color: var(--ga-fg-muted, #a1a1a1);",
		"    max-width: 42rem;",
		"  }",
		"",
		"  .toc {",
		"    margin-bottom: 3rem;",
		"  }",
		"",
		"  .toc ul {",
		"    list-style: none;",
		"    display: flex;",
		"    flex-wrap: wrap;",
		"    gap: 0.5rem 1rem;",
		"    padding: 0;",
		"    margin: 0;",
		"    font-size: 0.9rem;",
		"  }",
		"",
		"  section {",
		"    margin-bottom: 3.5rem;",
		"    scroll-margin-top: 1.5rem;",
		"  }",
		"",
		"  h2 {",
		"    font-size: 1.35rem;",
		"    letter-spacing: -0.01em;",
		"    margin-bottom: 0.75rem;",
		"  }",
		"",
		"  .summary {",
		"    color: var(--ga-fg-muted, #a1a1a1);",
		"  }",
		"",
		"  code {",
		"    font-family: ui-monospace, SFMono-Regular, \"SF Mono\", Menlo, monospace;",
		"    font-size: 0.9em;",
		"  }",
		"",
		"  pre {",
		"    margin: 0 0 1rem;",
		"    overflow-x: auto;",
		"    font-family: ui-monospace, SFMono-Regular, \"SF Mono\", Menlo, monospace;",
		"    font-size: 0.85rem;",
		"    line-height: 1.65;",
		"    white-space: pre;",
		"  }",
		"",
		"  pre.syntax {",
		"    color: var(--ga-accent, #3b82f6);",
		"    margin-bottom: 0.75rem;",
		"  }",
		"",
		"  .flags {",
		"    margin: 0 0 1rem;",
		"  }",
		"",
		"  .flags dt {",
		"    margin-top: 0.5rem;",
		"  }",
		"",
		"  .flags dd {",
		"    margin: 0.15rem 0 0 1.25rem;",
		"    color: var(--ga-fg-muted, #a1a1a1);",
		"  }",
		"",
		"  .subcommands {",
		"    font-size: 0.9rem;",
		"  }",
		"",
		"  ol {",
		"    padding-left: 1.25rem;",
		"  }",
		"",
		"  footer {",
		"    margin-top: 4rem;",
		"  }",
		"</style>",
	)
}
