package main

import (
	"slices"
	"strings"

	"github.com/gaarutyunov/epos/internal/skillfile"
)

// generatedBy is the banner the page carries, so nobody edits the output.
const generatedBy = "// Generated by `go run ./internal/docsgen` from the Skillfile instruction\n" +
	"// table in internal/skillfile/reference.go (SPEC.md 14.1). Do not edit by\n" +
	"// hand: CI regenerates this page and fails if the result differs.\n"

// render builds the whole page.
//
// Byte-stable by construction: every list it walks is a slice, nothing here
// ranges a map without sorting first, and the only newline written anywhere is
// "\n" — the drift check is worthless if the same inputs can produce two
// different files, and a page whose line endings came from runtime.GOOS would
// fail on exactly one leg of the CI matrix.
func render() []byte {
	ref := skillfile.NewReference()
	p := &page{}

	p.frontmatter()
	p.header()
	p.contents(ref)
	p.syntax(ref)
	p.sources(ref)
	for _, doc := range ref.Instructions {
		p.instruction(doc)
	}
	for _, topic := range ref.Topics {
		p.topic(topic)
	}
	p.footer()
	p.styles()

	return []byte(p.b.String())
}

// page accumulates the file.
type page struct {
	b strings.Builder
}

// w writes one line.
func (p *page) w(lines ...string) {
	for _, line := range lines {
		p.b.WriteString(line)
		p.b.WriteString("\n")
	}
}

func (p *page) frontmatter() {
	p.w(
		"---",
		strings.TrimRight(generatedBy, "\n"),
		`import Base from "../layouts/Base.astro";`,
		"",
		"// BASE_URL carries a trailing slash only when `base` was written with one,",
		"// so joining by hand is what keeps a link off /eposskillfile.",
		"const href = (path: string) =>",
		"  `${import.meta.env.BASE_URL.replace(/\\/$/, \"\")}/${path}`;",
		"---",
		"",
	)
}

func (p *page) header() {
	p.w(
		`<Base`,
		`  title="Skillfile reference — Epos"`,
		`  description="Every Skillfile instruction with its syntax and a worked example: FROM, COPY, RM, APPEND, REPLACE, PATCH, AWK, SET, UNSET and ARG, plus multi-stage composition and the values model."`,
		`>`,
		`  <p class="back"><a href={href("")}>← Epos</a></p>`,
		"",
		`  <header class="hero">`,
		`    <ga-badge color="blue">Reference</ga-badge>`,
		`    <h1>Skillfile reference</h1>`,
		`    <p class="lede">`,
		`      A Skillfile derives one skill from another. It reads like a Dockerfile and`,
		`      builds like a pure function: nothing executes, and the same bases,`,
		`      Skillfile and context always produce the same artifact.`,
		`    </p>`,
		`  </header>`,
		"",
	)
}

// contents is the in-page index.
func (p *page) contents(ref skillfile.Reference) {
	p.w(`  <nav class="toc" aria-label="On this page">`, `    <ul>`)
	p.w(`      <li><a href="#syntax">Syntax</a></li>`)
	p.w(`      <li><a href="#from-sources">FROM sources</a></li>`)
	for _, doc := range ref.Instructions {
		p.w(`      <li><a href="#` + slug(doc.Op) + `"><code>` + escape(doc.Op) + `</code></a></li>`)
	}
	for _, topic := range ref.Topics {
		p.w(`      <li><a href="#` + escape(topic.Slug) + `">` + escape(topic.Title) + `</a></li>`)
	}
	p.w(`    </ul>`, `  </nav>`, "")
}

func (p *page) syntax(ref skillfile.Reference) {
	p.w(`  <section id="syntax">`, `    <h2>Syntax</h2>`)
	for _, para := range ref.Syntax {
		p.w(`    <p>` + inline(para) + `</p>`)
	}
	p.w(`  </section>`, "")
}

// sources renders the FROM table of SPEC.md 8.3.
func (p *page) sources(ref skillfile.Reference) {
	p.w(
		`  <section id="from-sources">`,
		`    <h2>FROM sources</h2>`,
		`    <p>`,
		`      `+inline("A `FROM` reference is one of four things. Only the OCI scheme touches a "+
			"registry, so a Skillfile built on local or git bases is a complete, standalone workflow."),
		`    </p>`,
		`    <ga-table`,
		`      columns='[&#123;"label":"Source"&#125;,&#123;"label":"Reference","mono":true&#125;,&#123;"label":"Pin","width":"170px"&#125;]'`,
		`    >`,
	)
	for _, src := range ref.Sources {
		p.w(
			`      <div>`,
			`        <div>`,
			`          <strong>`+escape(src.Scheme)+`</strong>`,
			`          <div class="cell-note">`+inline(src.Notes)+`</div>`,
			`        </div>`,
			`        <span>`+escape(src.Example)+`</span>`,
			`        <span>`+escape(src.Pin)+`</span>`,
			`      </div>`,
		)
	}
	p.w(`    </ga-table>`, `  </section>`, "")
}

// instruction renders one row of the instruction table.
func (p *page) instruction(doc skillfile.InstructionDoc) {
	p.w(
		`  <section id="`+slug(doc.Op)+`">`,
		`    <h2><code>`+escape(doc.Op)+`</code></h2>`,
		`    <pre class="syntax">`+escape(doc.Syntax)+`</pre>`,
		`    <p class="summary">`+inline(doc.Summary)+`</p>`,
	)

	if len(doc.Flags) > 0 {
		p.w(`    <dl class="flags">`)
		for _, flag := range doc.Flags {
			p.w(
				`      <dt><code>--`+escape(flag.Name)+`=`+escape(flag.Value)+`</code></dt>`,
				`      <dd>`+inline(flag.Summary)+`</dd>`,
			)
		}
		p.w(`    </dl>`)
	}

	for _, note := range doc.Notes {
		p.w(`    <p>` + inline(note) + `</p>`)
	}

	p.example(doc.Example)
	p.w(`  </section>`, "")
}

// topic renders a section that is not one instruction.
func (p *page) topic(topic skillfile.TopicDoc) {
	p.w(
		`  <section id="`+escape(topic.Slug)+`">`,
		`    <h2>`+escape(topic.Title)+`</h2>`,
	)
	for _, para := range topic.Body {
		p.w(`    <p>` + inline(para) + `</p>`)
	}
	if topic.Example != nil {
		p.example(*topic.Example)
	}
	p.w(`  </section>`, "")
}

// example renders a worked example: the context it runs against, the
// Skillfile, and what the build makes of them.
//
// Every one of these is executed by the skillfile package's tests against the
// real builder, so what the page shows is what the build does.
func (p *page) example(ex skillfile.Example) {
	if ex.Skillfile == "" {
		return
	}

	p.w(`    <ga-card padding="lg">`, `      <div class="example">`)

	p.w(`        <p class="label">Build context</p>`)
	for _, f := range ex.Context {
		p.file(f)
	}

	if len(ex.BuildArgs) > 0 {
		names := make([]string, 0, len(ex.BuildArgs))
		for name := range ex.BuildArgs {
			names = append(names, name)
		}
		// Sorted, because a Go map's iteration order is randomised and this
		// output has to be byte-identical every run.
		slices.Sort(names)

		var args []string
		for _, name := range names {
			args = append(args, "--build-arg "+name+"="+ex.BuildArgs[name])
		}
		p.w(
			`        <p class="label">Built with</p>`,
			`        <pre>`+escape("epos build "+strings.Join(args, " ")+" .")+`</pre>`,
		)
	}

	p.w(
		`        <p class="label">Skillfile</p>`,
		`        <pre>`+escape(strings.TrimRight(ex.Skillfile, "\n"))+`</pre>`,
	)

	if ex.Result.Path != "" {
		p.w(`        <p class="label">Result</p>`)
		p.file(ex.Result)
	}
	for _, absent := range ex.Absent {
		p.w(`        <p class="label">Removed</p>`,
			`        <p class="filename"><code>`+escape(absent)+`</code></p>`)
	}
	if len(ex.Warnings) > 0 {
		p.w(`        <p class="label">On stderr</p>`)
		var lines []string
		for _, warning := range ex.Warnings {
			lines = append(lines, "warning: "+warning)
		}
		p.w(`        <pre>` + escape(strings.Join(lines, "\n")) + `</pre>`)
	}

	p.w(`      </div>`, `    </ga-card>`)
}

// file renders one named file of an example.
func (p *page) file(f skillfile.ExampleFile) {
	p.w(
		`        <p class="filename"><code>`+escape(f.Path)+`</code></p>`,
		`        <pre>`+escape(strings.TrimRight(f.Body, "\n"))+`</pre>`,
	)
}

func (p *page) footer() {
	p.w(
		`  <footer>`,
		`    <p>`,
		`      <ga-button variant="primary" href="https://github.com/gaarutyunov/epos">`,
		`        Source on GitHub`,
		`      </ga-button>`,
		`    </p>`,
		`  </footer>`,
		`</Base>`,
		"",
	)
}

// styles is the page's scoped CSS.
//
// Written out rather than escaped: a <style> element is raw text to Astro, so
// the braces here are CSS braces and must stay braces.
func (p *page) styles() {
	p.w(
		"<style>",
		"  .back {",
		"    font-size: 0.9rem;",
		"    margin: 0 0 2rem;",
		"  }",
		"",
		"  .hero {",
		"    margin-bottom: 2.5rem;",
		"  }",
		"",
		"  h1 {",
		"    font-size: clamp(1.9rem, 5vw, 2.6rem);",
		"    line-height: 1.15;",
		"    letter-spacing: -0.02em;",
		"    margin: 1rem 0 0.75rem;",
		"  }",
		"",
		"  .lede {",
		"    font-size: 1.1rem;",
		"    color: var(--ga-fg-muted, #a1a1a1);",
		"    max-width: 42rem;",
		"  }",
		"",
		"  .toc {",
		"    margin-bottom: 3rem;",
		"  }",
		"",
		"  .toc ul {",
		"    list-style: none;",
		"    display: flex;",
		"    flex-wrap: wrap;",
		"    gap: 0.5rem 1rem;",
		"    padding: 0;",
		"    margin: 0;",
		"    font-size: 0.9rem;",
		"  }",
		"",
		"  section {",
		"    margin-bottom: 3.5rem;",
		"    scroll-margin-top: 1.5rem;",
		"  }",
		"",
		"  h2 {",
		"    font-size: 1.35rem;",
		"    letter-spacing: -0.01em;",
		"    margin-bottom: 0.75rem;",
		"  }",
		"",
		"  .summary {",
		"    color: var(--ga-fg-muted, #a1a1a1);",
		"  }",
		"",
		"  code {",
		"    font-family: ui-monospace, SFMono-Regular, \"SF Mono\", Menlo, monospace;",
		"    font-size: 0.9em;",
		"  }",
		"",
		"  pre {",
		"    margin: 0 0 1rem;",
		"    overflow-x: auto;",
		"    font-family: ui-monospace, SFMono-Regular, \"SF Mono\", Menlo, monospace;",
		"    font-size: 0.85rem;",
		"    line-height: 1.65;",
		"    white-space: pre;",
		"  }",
		"",
		"  pre.syntax {",
		"    color: var(--ga-accent, #3b82f6);",
		"    margin-bottom: 0.75rem;",
		"  }",
		"",
		"  .flags {",
		"    margin: 0 0 1rem;",
		"  }",
		"",
		"  .flags dt {",
		"    margin-top: 0.5rem;",
		"  }",
		"",
		"  .flags dd {",
		"    margin: 0.15rem 0 0 1.25rem;",
		"    color: var(--ga-fg-muted, #a1a1a1);",
		"  }",
		"",
		"  .example .label {",
		"    margin: 1.25rem 0 0.35rem;",
		"    font-size: 0.75rem;",
		"    letter-spacing: 0.06em;",
		"    text-transform: uppercase;",
		"    color: var(--ga-fg-muted, #a1a1a1);",
		"  }",
		"",
		"  .example .label:first-child {",
		"    margin-top: 0;",
		"  }",
		"",
		"  .example .filename {",
		"    margin: 0 0 0.25rem;",
		"    font-size: 0.8rem;",
		"    color: var(--ga-fg-muted, #a1a1a1);",
		"  }",
		"",
		"  .cell-note {",
		"    font-size: 0.85rem;",
		"    color: var(--ga-fg-muted, #a1a1a1);",
		"  }",
		"",
		"  footer {",
		"    margin-top: 4rem;",
		"  }",
		"</style>",
	)
}

// slug is an instruction's anchor.
func slug(op string) string {
	return strings.ToLower(op)
}

// escape makes text safe to drop into the Astro template.
//
// The braces are the reason this exists rather than html.EscapeString: Astro
// reads a bare `{` in markup as the start of a JavaScript expression, and this
// page is full of them — `{{ .Values.model }}` in a template, `{ print }` in an
// AWK script, `{name}` in a syntax line. As numeric references they reach the
// HTML parser as ordinary text, so they render and copy as the braces they are.
func escape(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		switch r {
		case '&':
			b.WriteString("&amp;")
		case '<':
			b.WriteString("&lt;")
		case '>':
			b.WriteString("&gt;")
		case '"':
			b.WriteString("&quot;")
		case '{':
			b.WriteString("&#123;")
		case '}':
			b.WriteString("&#125;")
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

// inline escapes prose and renders the two markers the table's text uses:
// `code` spans and **strong** runs.
func inline(s string) string {
	return emphasise(emphasise(escape(s), "`", "code"), "**", "strong")
}

// emphasise wraps every delimited run in tag.
//
// An unpaired delimiter leaves the text exactly as it was rather than emitting
// half an element: a stray backtick in a note is a typo, and unbalanced markup
// would be a broken page.
func emphasise(s, delim, tag string) string {
	parts := strings.Split(s, delim)
	if len(parts)%2 == 0 {
		return s
	}

	var b strings.Builder
	for i, part := range parts {
		if i%2 == 0 {
			b.WriteString(part)
			continue
		}
		b.WriteString("<" + tag + ">")
		b.WriteString(part)
		b.WriteString("</" + tag + ">")
	}
	return b.String()
}
