package main

import (
	"slices"
	"strings"

	"github.com/gaarutyunov/epos/internal/skillfile"
)

// skillfileBanner is the banner the page carries, so nobody edits the output.
const skillfileBanner = "// Generated by `go run ./internal/docsgen` from the Skillfile instruction\n" +
	"// table in internal/skillfile/reference.go (SPEC.md 14.1). Do not edit by\n" +
	"// hand: CI regenerates this page and fails if the result differs.\n"

// renderSkillfile builds the whole page.
func renderSkillfile() []byte {
	ref := skillfile.NewReference()
	p := &page{}

	p.frontmatter(skillfileBanner)
	p.header()
	p.syntax(ref)
	p.sources(ref)
	for _, doc := range ref.Instructions {
		p.instruction(doc)
	}
	for _, topic := range ref.Topics {
		p.topic(topic)
	}
	p.contents(ref)
	p.docClose()
	p.styles()

	return []byte(p.b.String())
}

func (p *page) header() {
	p.docOpen(
		"Skillfile reference — Epos",
		"Every Skillfile instruction with its syntax and a worked example: FROM, COPY, RM, APPEND, REPLACE, PATCH, AWK, SET, UNSET and ARG, plus multi-stage composition and the values model.",
		"Skillfile reference",
	)
	p.heading("Skillfile reference", []string{
		`    A Skillfile derives one skill from another. It reads like a`,
		`    Dockerfile and builds like a pure function: nothing executes, and`,
		`    the same bases, Skillfile and context always produce the same`,
		`    artifact.`,
	})
}

// contents is the sidebar: an index of the page, plus the way out of it.
//
// Built from the same instruction table the page is, so an instruction added to
// internal/skillfile appears here without an edit. 3300 words of reference had
// no within-page navigation at all; this is the column that earns its width.
func (p *page) contents(ref skillfile.Reference) {
	p.asideStart()

	links := []asideLink{
		{attr: `"#syntax"`, label: "Syntax"},
		{attr: `"#from-sources"`, label: "FROM sources"},
	}
	for _, doc := range ref.Instructions {
		links = append(links, asideLink{
			attr: `"#` + slug(doc.Op) + `"`, label: doc.Op, code: true,
		})
	}
	for _, topic := range ref.Topics {
		links = append(links, asideLink{
			attr: `"#` + escape(topic.Slug) + `"`, label: topic.Title,
		})
	}
	p.asideSection("On this page", links)

	p.asideSection("Elsewhere", []asideLink{
		{attr: `{href("quickstart")}`, label: "Quick start"},
		{attr: `{href("cli")}`, label: "CLI reference"},
	})
}

func (p *page) syntax(ref skillfile.Reference) {
	p.w(`  <section id="syntax">`, `    <h2>Syntax</h2>`)
	for _, para := range ref.Syntax {
		p.w(`    <p>` + inline(para) + `</p>`)
	}
	p.w(`  </section>`, "")
}

// sources renders the FROM table of SPEC.md 8.3.
func (p *page) sources(ref skillfile.Reference) {
	p.w(
		`  <section id="from-sources">`,
		`    <h2>FROM sources</h2>`,
		`    <p>`,
		`      `+inline("A `FROM` reference is one of four things. Only the OCI scheme touches a "+
			"registry, so a Skillfile built on local or git bases is a complete, standalone workflow."),
		`    </p>`,
		`    <ga-table`,
		`      columns='[&#123;"label":"Source"&#125;,&#123;"label":"Reference","mono":true&#125;,&#123;"label":"Pin","width":"170px"&#125;]'`,
		`    >`,
	)
	for _, src := range ref.Sources {
		p.w(
			`      <div>`,
			`        <div>`,
			`          <strong>`+escape(src.Scheme)+`</strong>`,
			`          <div class="cell-note">`+inline(src.Notes)+`</div>`,
			`        </div>`,
			`        <span>`+escape(src.Example)+`</span>`,
			`        <span>`+escape(src.Pin)+`</span>`,
			`      </div>`,
		)
	}
	p.w(`    </ga-table>`, `  </section>`, "")
}

// instruction renders one row of the instruction table.
func (p *page) instruction(doc skillfile.InstructionDoc) {
	p.w(
		`  <section id="`+slug(doc.Op)+`">`,
		`    <h2><code>`+escape(doc.Op)+`</code></h2>`,
		`    <pre class="syntax">`+escape(doc.Syntax)+`</pre>`,
		`    <p class="summary">`+inline(doc.Summary)+`</p>`,
	)

	if len(doc.Flags) > 0 {
		p.w(`    <dl class="flags">`)
		for _, flag := range doc.Flags {
			p.w(
				`      <dt><code>--`+escape(flag.Name)+`=`+escape(flag.Value)+`</code></dt>`,
				`      <dd>`+inline(flag.Summary)+`</dd>`,
			)
		}
		p.w(`    </dl>`)
	}

	for _, note := range doc.Notes {
		p.w(`    <p>` + inline(note) + `</p>`)
	}

	p.example(doc.Example)
	p.w(`  </section>`, "")
}

// topic renders a section that is not one instruction.
func (p *page) topic(topic skillfile.TopicDoc) {
	p.w(
		`  <section id="`+escape(topic.Slug)+`">`,
		`    <h2>`+escape(topic.Title)+`</h2>`,
	)
	for _, para := range topic.Body {
		p.w(`    <p>` + inline(para) + `</p>`)
	}
	if topic.Example != nil {
		p.example(*topic.Example)
	}
	p.w(`  </section>`, "")
}

// example renders a worked example: the context it runs against, the
// Skillfile, and what the build makes of them.
//
// Every one of these is executed by the skillfile package's tests against the
// real builder, so what the page shows is what the build does.
func (p *page) example(ex skillfile.Example) {
	if ex.Skillfile == "" {
		return
	}

	p.w(`    <ga-card padding="lg">`, `      <div class="example">`)

	p.w(`        <p class="label">Build context</p>`)
	for _, f := range ex.Context {
		p.file(f)
	}

	if len(ex.BuildArgs) > 0 {
		names := make([]string, 0, len(ex.BuildArgs))
		for name := range ex.BuildArgs {
			names = append(names, name)
		}
		// Sorted, because a Go map's iteration order is randomised and this
		// output has to be byte-identical every run.
		slices.Sort(names)

		var args []string
		for _, name := range names {
			args = append(args, "--build-arg "+name+"="+ex.BuildArgs[name])
		}
		p.w(
			`        <p class="label">Built with</p>`,
			`        <pre>`+escape("epos build "+strings.Join(args, " ")+" .")+`</pre>`,
		)
	}

	p.w(
		`        <p class="label">Skillfile</p>`,
		`        <pre>`+escape(strings.TrimRight(ex.Skillfile, "\n"))+`</pre>`,
	)

	if ex.Result.Path != "" {
		p.w(`        <p class="label">Result</p>`)
		p.file(ex.Result)
	}
	for _, absent := range ex.Absent {
		p.w(`        <p class="label">Removed</p>`,
			`        <p class="filename"><code>`+escape(absent)+`</code></p>`)
	}
	if len(ex.Warnings) > 0 {
		p.w(`        <p class="label">On stderr</p>`)
		var lines []string
		for _, warning := range ex.Warnings {
			lines = append(lines, "warning: "+warning)
		}
		p.w(`        <pre>` + escape(strings.Join(lines, "\n")) + `</pre>`)
	}

	p.w(`      </div>`, `    </ga-card>`)
}

// file renders one named file of an example.
func (p *page) file(f skillfile.ExampleFile) {
	p.w(
		`        <p class="filename"><code>`+escape(f.Path)+`</code></p>`,
		`        <pre>`+escape(strings.TrimRight(f.Body, "\n"))+`</pre>`,
	)
}

// styles is the page's scoped CSS.
//
// Written out rather than escaped: a <style> element is raw text to Astro, so
// the braces here are CSS braces and must stay braces.
// styles is what this page needs on top of the shared chrome in the layout.
func (p *page) styles() {
	p.w(
		"<style>",
		"  .summary {",
		"    color: var(--ga-muted, #878787);",
		"  }",
		"",
		"  pre.syntax {",
		"    color: var(--ga-accent, #54a2ff);",
		"    margin-bottom: var(--ga-space-3, 12px);",
		"  }",
		"",
		"  .flags {",
		"    margin: 0 0 var(--ga-space-4, 16px);",
		"  }",
		"",
		"  .flags dt {",
		"    margin-top: var(--ga-space-2, 8px);",
		"    font-family: var(--ga-font-mono);",
		"    font-size: var(--ga-fs-sm, 14px);",
		"  }",
		"",
		"  .flags dd {",
		"    margin: 0.15rem 0 0 1.25rem;",
		"    color: var(--ga-muted, #878787);",
		"  }",
		"",
		"  .example {",
		"    margin-bottom: var(--ga-space-4, 16px);",
		"  }",
		"",
		"  .label {",
		"    margin: var(--ga-space-4, 16px) 0 var(--ga-space-2, 8px);",
		"    font-family: var(--ga-font-mono);",
		"    font-size: var(--ga-fs-xs, 12px);",
		"    text-transform: uppercase;",
		"    color: var(--ga-fg, #ededed);",
		"  }",
		"",
		"  .cell-note {",
		"    font-size: var(--ga-fs-sm, 14px);",
		"    color: var(--ga-muted, #878787);",
		"  }",
		"",
		"  .filename {",
		"    margin: var(--ga-space-4, 16px) 0 var(--ga-space-2, 8px);",
		"    font-family: var(--ga-font-mono);",
		"    font-size: var(--ga-fs-xs, 12px);",
		"    text-transform: uppercase;",
		"    color: var(--ga-dim, #454545);",
		"  }",
		"",
		"  .arrow {",
		"    font-family: var(--ga-font-mono);",
		"    font-size: var(--ga-fs-xs, 12px);",
		"  }",
		"</style>",
	)
}

// slug is an instruction's anchor.
func slug(op string) string {
	return strings.ToLower(op)
}
