// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/packaging/domain"
)

// PackageSkillInput is the input DTO for the PackageSkill use case.
type PackageSkillInput struct {
	Request domain.PackageRequest `json:"request"`
}

// PackageSkillOutput is the output DTO for the PackageSkill use case.
type PackageSkillOutput struct {
	Artifact domain.PackagedArtifact `json:"artifact"`
}

// PackageSkillUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type PackageSkillUseCase interface {
	PackageSkill(input PackageSkillInput) (PackageSkillOutput, error)
}
