// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/packaging/domain"
)

// PushSkillInput is the input DTO for the PushSkill use case.
type PushSkillInput struct {
	Ref      domain.OciRef        `json:"ref"`
	Artifact domain.SkillArtifact `json:"artifact"`
}

// PushSkillOutput is the output DTO for the PushSkill use case.
type PushSkillOutput struct {
	Pushed domain.PackagedArtifact `json:"pushed"`
}

// PushSkillUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type PushSkillUseCase interface {
	PushSkill(input PushSkillInput) (PushSkillOutput, error)
}
