// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/packaging/domain"
)

// ValidateSkillInput is the input DTO for the ValidateSkill use case.
type ValidateSkillInput struct {
	Artifact domain.SkillArtifact `json:"artifact"`
}

// ValidateSkillOutput is the output DTO for the ValidateSkill use case.
type ValidateSkillOutput struct {
	Report domain.ValidationReport `json:"report"`
}

// ValidateSkillUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type ValidateSkillUseCase interface {
	ValidateSkill(input ValidateSkillInput) (ValidateSkillOutput, error)
}
