// Code generated by MockGen. DO NOT EDIT.
// Source: discover.go
//
// Generated by this command:
//
//	mockgen -source=discover.go -destination=mocks_test.go -package=cli
//

// Package cli is a generated GoMock package.
package cli

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockregistryClient is a mock of registryClient interface.
type MockregistryClient struct {
	ctrl     *gomock.Controller
	recorder *MockregistryClientMockRecorder
	isgomock struct{}
}

// MockregistryClientMockRecorder is the mock recorder for MockregistryClient.
type MockregistryClientMockRecorder struct {
	mock *MockregistryClient
}

// NewMockregistryClient creates a new mock instance.
func NewMockregistryClient(ctrl *gomock.Controller) *MockregistryClient {
	mock := &MockregistryClient{ctrl: ctrl}
	mock.recorder = &MockregistryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockregistryClient) EXPECT() *MockregistryClientMockRecorder {
	return m.recorder
}

// Annotations mocks base method.
func (m *MockregistryClient) Annotations(ctx context.Context, repository, reference string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Annotations", ctx, repository, reference)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Annotations indicates an expected call of Annotations.
func (mr *MockregistryClientMockRecorder) Annotations(ctx, repository, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Annotations", reflect.TypeOf((*MockregistryClient)(nil).Annotations), ctx, repository, reference)
}

// Catalog mocks base method.
func (m *MockregistryClient) Catalog(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Catalog", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Catalog indicates an expected call of Catalog.
func (mr *MockregistryClientMockRecorder) Catalog(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Catalog", reflect.TypeOf((*MockregistryClient)(nil).Catalog), ctx)
}

// Tags mocks base method.
func (m *MockregistryClient) Tags(ctx context.Context, repository string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tags", ctx, repository)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tags indicates an expected call of Tags.
func (mr *MockregistryClientMockRecorder) Tags(ctx, repository any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tags", reflect.TypeOf((*MockregistryClient)(nil).Tags), ctx, repository)
}
