// Code generated by sysgo; DO NOT EDIT.

package domain

// NewCatalog is a factory that constructs a valid Catalog aggregate.
// Add invariant checks here; return an error when they are violated.
func NewCatalog() (*Catalog, error) {
	return &Catalog{}, nil
}
