// Code generated by sysgo; DO NOT EDIT.

package domain

// Catalog is an aggregate root. It is the consistency boundary for its
// contained entities and value objects; mutate it only through its methods.
type Catalog struct {
	ID    string      `json:"id"`
	Cards []SkillCard `json:"cards"`
}
