// Code generated by sysgo; DO NOT EDIT.

package domain

// Filter is a value object: immutable and compared by value.
type Filter struct {
	Keyword  string `json:"keyword"`
	Registry string `json:"registry"`
}

// Equal reports whether two Filter values are equal.
func (f Filter) Equal(other Filter) bool {
	return f == other
}
