// Code generated by sysgo; DO NOT EDIT.

package domain

// ListingRequest is a value object: immutable and compared by value.
type ListingRequest struct {
	Filter Filter `json:"filter"`
}

// Equal reports whether two ListingRequest values are equal.
func (l ListingRequest) Equal(other ListingRequest) bool {
	return l == other
}
