// Code generated by sysgo; DO NOT EDIT.

package domain

// SkillCard is a value object: immutable and compared by value.
type SkillCard struct {
	Name        string `json:"name"`
	Version     string `json:"version"`
	Description string `json:"description"`
	Registry    string `json:"registry"`
	Downloads   int64  `json:"downloads"`
}

// Equal reports whether two SkillCard values are equal.
func (s SkillCard) Equal(other SkillCard) bool {
	return s == other
}
