// Code generated by sysgo; DO NOT EDIT.

package domain

// ComposeRequest is a value object: immutable and compared by value.
type ComposeRequest struct {
	StackID string `json:"stackId"`
	Values  string `json:"values"`
}

// Equal reports whether two ComposeRequest values are equal.
func (c ComposeRequest) Equal(other ComposeRequest) bool {
	return c == other
}
