// Code generated by sysgo; DO NOT EDIT.

package domain

// Layer is an aggregate root. It is the consistency boundary for its
// contained entities and value objects; mutate it only through its methods.
type Layer struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	Kind       LayerKind   `json:"kind"`
	Source     SourceKind  `json:"source"`
	Pin        Pin         `json:"pin"`
	Operations []Operation `json:"operations"`
}
