// Code generated by sysgo; DO NOT EDIT.

package domain

// NewLayerStack is a factory that constructs a valid LayerStack aggregate.
// Add invariant checks here; return an error when they are violated.
func NewLayerStack() (*LayerStack, error) {
	return &LayerStack{}, nil
}
