// Code generated by sysgo; DO NOT EDIT.

package domain

// LayerKind is a value object: immutable and compared by value.
type LayerKind struct {
	Value string `json:"value"`
}

// Equal reports whether two LayerKind values are equal.
func (l LayerKind) Equal(other LayerKind) bool {
	return l == other
}
