// Code generated by sysgo; DO NOT EDIT.

package domain

// LayerStack is an aggregate root. It is the consistency boundary for its
// contained entities and value objects; mutate it only through its methods.
type LayerStack struct {
	ID     string  `json:"id"`
	Layers []Layer `json:"layers"`
}
