// Code generated by sysgo; DO NOT EDIT.

package domain

// NewLayer is a factory that constructs a valid Layer aggregate.
// Add invariant checks here; return an error when they are violated.
func NewLayer() (*Layer, error) {
	return &Layer{}, nil
}
