// Code generated by sysgo; DO NOT EDIT.

package domain

// MergedSkill is a value object: immutable and compared by value.
type MergedSkill struct {
	SkillID    string   `json:"skillId"`
	Provenance []string `json:"provenance"`
}
