// Code generated by sysgo; DO NOT EDIT.

package domain

// Operation is a value object: immutable and compared by value.
type Operation struct {
	Op          string `json:"op"`
	Target      string `json:"target"`
	PayloadPath string `json:"payloadPath"`
	Content     string `json:"content"`
	Pattern     string `json:"pattern"`
	Replacement string `json:"replacement"`
	Required    bool   `json:"required"`
}

// Equal reports whether two Operation values are equal.
func (o Operation) Equal(other Operation) bool {
	return o == other
}
