// Code generated by sysgo; DO NOT EDIT.

package domain

// Pin is a value object: immutable and compared by value.
type Pin struct {
	SourceType SourceKind `json:"sourceType"`
	Source     string     `json:"source"`
	Version    string     `json:"version"`
	Digest     string     `json:"digest"`
	Commit     string     `json:"commit"`
	TreeSha    string     `json:"treeSha"`
	Subpath    string     `json:"subpath"`
}

// Equal reports whether two Pin values are equal.
func (p Pin) Equal(other Pin) bool {
	return p == other
}
