// Code generated by sysgo; DO NOT EDIT.

package domain

// PinRecord is a value object: immutable and compared by value.
type PinRecord struct {
	Name string `json:"name"`
	Pin  Pin    `json:"pin"`
}

// Equal reports whether two PinRecord values are equal.
func (p PinRecord) Equal(other PinRecord) bool {
	return p == other
}
