// Code generated by sysgo; DO NOT EDIT.

package domain

// SourceKind is a value object: immutable and compared by value.
type SourceKind struct {
	Value string `json:"value"`
}

// Equal reports whether two SourceKind values are equal.
func (s SourceKind) Equal(other SourceKind) bool {
	return s == other
}
