// Code generated by sysgo; DO NOT EDIT.

package domain

// DiscoveryMode is a value object: immutable and compared by value.
type DiscoveryMode struct {
	Value string `json:"value"`
}

// Equal reports whether two DiscoveryMode values are equal.
func (d DiscoveryMode) Equal(other DiscoveryMode) bool {
	return d == other
}
