// Code generated by sysgo; DO NOT EDIT.

package domain

// ListingSecret is a value object: immutable and compared by value.
type ListingSecret struct {
	UsernameEnv string `json:"usernameEnv"`
	TokenEnv    string `json:"tokenEnv"`
}

// Equal reports whether two ListingSecret values are equal.
func (l ListingSecret) Equal(other ListingSecret) bool {
	return l == other
}
