// Code generated by sysgo; DO NOT EDIT.

package domain

// ProxyResponse is a value object: immutable and compared by value.
type ProxyResponse struct {
	Status int64  `json:"status"`
	Body   string `json:"body"`
}

// Equal reports whether two ProxyResponse values are equal.
func (p ProxyResponse) Equal(other ProxyResponse) bool {
	return p == other
}
