// Code generated by sysgo; DO NOT EDIT.

package domain

// ProxyRequest is a value object: immutable and compared by value.
type ProxyRequest struct {
	Method    string `json:"method"`
	Repo      string `json:"repo"`
	Reference string `json:"reference"`
}

// Equal reports whether two ProxyRequest values are equal.
func (p ProxyRequest) Equal(other ProxyRequest) bool {
	return p == other
}
