// Code generated by sysgo; DO NOT EDIT.

package domain

// RegistryEntry is a value object: immutable and compared by value.
type RegistryEntry struct {
	Name         string        `json:"name"`
	URL          string        `json:"url"`
	Discovery    DiscoveryMode `json:"discovery"`
	Repositories []string      `json:"repositories"`
	Namespaces   []string      `json:"namespaces"`
}
