// Code generated by sysgo; DO NOT EDIT.

package domain

// RegistrationIndex is an aggregate root. It is the consistency boundary for its
// contained entities and value objects; mutate it only through its methods.
type RegistrationIndex struct {
	ID      string          `json:"id"`
	Entries []RegistryEntry `json:"entries"`
}
