// Code generated by sysgo; DO NOT EDIT.

package domain

// NewRegistrationIndex is a factory that constructs a valid RegistrationIndex aggregate.
// Add invariant checks here; return an error when they are violated.
func NewRegistrationIndex() (*RegistrationIndex, error) {
	return &RegistrationIndex{}, nil
}
