// Code generated by MockGen. DO NOT EDIT.
// Source: stats.go
//
// Generated by this command:
//
//	mockgen -source=stats.go -destination=mocks_test.go -package=catalog
//

// Package catalog is a generated GoMock package.
package catalog

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStats is a mock of Stats interface.
type MockStats struct {
	ctrl     *gomock.Controller
	recorder *MockStatsMockRecorder
	isgomock struct{}
}

// MockStatsMockRecorder is the mock recorder for MockStats.
type MockStatsMockRecorder struct {
	mock *MockStats
}

// NewMockStats creates a new mock instance.
func NewMockStats(ctrl *gomock.Controller) *MockStats {
	mock := &MockStats{ctrl: ctrl}
	mock.recorder = &MockStatsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStats) EXPECT() *MockStatsMockRecorder {
	return m.recorder
}

// Pulls mocks base method.
func (m *MockStats) Pulls(ctx context.Context) (Counts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pulls", ctx)
	ret0, _ := ret[0].(Counts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pulls indicates an expected call of Pulls.
func (mr *MockStatsMockRecorder) Pulls(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pulls", reflect.TypeOf((*MockStats)(nil).Pulls), ctx)
}
