// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gaarutyunov/epos/internal/registry (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=mocks_registry_test.go -package=catalog github.com/gaarutyunov/epos/internal/registry Client
//

// Package catalog is a generated GoMock package.
package catalog

import (
	context "context"
	reflect "reflect"

	registry "github.com/gaarutyunov/epos/internal/registry"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Annotations mocks base method.
func (m *MockClient) Annotations(ctx context.Context, repository, reference string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Annotations", ctx, repository, reference)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Annotations indicates an expected call of Annotations.
func (mr *MockClientMockRecorder) Annotations(ctx, repository, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Annotations", reflect.TypeOf((*MockClient)(nil).Annotations), ctx, repository, reference)
}

// Catalog mocks base method.
func (m *MockClient) Catalog(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Catalog", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Catalog indicates an expected call of Catalog.
func (mr *MockClientMockRecorder) Catalog(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Catalog", reflect.TypeOf((*MockClient)(nil).Catalog), ctx)
}

// FetchContent mocks base method.
func (m *MockClient) FetchContent(ctx context.Context, repository, reference string) (registry.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchContent", ctx, repository, reference)
	ret0, _ := ret[0].(registry.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchContent indicates an expected call of FetchContent.
func (mr *MockClientMockRecorder) FetchContent(ctx, repository, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchContent", reflect.TypeOf((*MockClient)(nil).FetchContent), ctx, repository, reference)
}

// Manifest mocks base method.
func (m *MockClient) Manifest(ctx context.Context, repository, reference string) (registry.Manifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Manifest", ctx, repository, reference)
	ret0, _ := ret[0].(registry.Manifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Manifest indicates an expected call of Manifest.
func (mr *MockClientMockRecorder) Manifest(ctx, repository, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Manifest", reflect.TypeOf((*MockClient)(nil).Manifest), ctx, repository, reference)
}

// Tags mocks base method.
func (m *MockClient) Tags(ctx context.Context, repository string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tags", ctx, repository)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tags indicates an expected call of Tags.
func (mr *MockClientMockRecorder) Tags(ctx, repository any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tags", reflect.TypeOf((*MockClient)(nil).Tags), ctx, repository)
}
