// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/frontend/domain"
)

// FilterCatalogInput is the input DTO for the FilterCatalog use case.
type FilterCatalogInput struct {
	Request domain.ListingRequest `json:"request"`
}

// FilterCatalogOutput is the output DTO for the FilterCatalog use case.
type FilterCatalogOutput struct {
	Listing domain.Listing `json:"listing"`
}

// FilterCatalogUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type FilterCatalogUseCase interface {
	FilterCatalog(input FilterCatalogInput) (FilterCatalogOutput, error)
}
