// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/frontend/domain"
)

// ListCatalogInput is the input DTO for the ListCatalog use case.
type ListCatalogInput struct {
	Request domain.ListingRequest `json:"request"`
}

// ListCatalogOutput is the output DTO for the ListCatalog use case.
type ListCatalogOutput struct {
	Listing domain.Listing `json:"listing"`
}

// ListCatalogUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type ListCatalogUseCase interface {
	ListCatalog(input ListCatalogInput) (ListCatalogOutput, error)
}
