// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/signing/domain"
)

// VerifySignatureInput is the input DTO for the VerifySignature use case.
type VerifySignatureInput struct {
	Request domain.VerifyRequest `json:"request"`
}

// VerifySignatureOutput is the output DTO for the VerifySignature use case.
type VerifySignatureOutput struct {
	Result domain.VerifyResult `json:"result"`
}

// VerifySignatureUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type VerifySignatureUseCase interface {
	VerifySignature(input VerifySignatureInput) (VerifySignatureOutput, error)
}
