// Code generated by sysgo; DO NOT EDIT.

package domain

// CountSnapshot is a value object: immutable and compared by value.
type CountSnapshot struct {
	Skill string `json:"skill"`
	Total int64  `json:"total"`
}

// Equal reports whether two CountSnapshot values are equal.
func (c CountSnapshot) Equal(other CountSnapshot) bool {
	return c == other
}
