// Code generated by sysgo; DO NOT EDIT.

package domain

// CountRequest is a value object: immutable and compared by value.
type CountRequest struct {
	Event PullEvent `json:"event"`
}

// Equal reports whether two CountRequest values are equal.
func (c CountRequest) Equal(other CountRequest) bool {
	return c == other
}
