// Code generated by sysgo; DO NOT EDIT.

package domain

// NewDownloadCounter is a factory that constructs a valid DownloadCounter aggregate.
// Add invariant checks here; return an error when they are violated.
func NewDownloadCounter() (*DownloadCounter, error) {
	return &DownloadCounter{}, nil
}
