// Code generated by sysgo; DO NOT EDIT.

package domain

// DownloadCounter is an aggregate root. It is the consistency boundary for its
// contained entities and value objects; mutate it only through its methods.
type DownloadCounter struct {
	ID    string `json:"id"`
	Skill string `json:"skill"`
	Count int64  `json:"count"`
}
