// Code generated by sysgo; DO NOT EDIT.

package domain

// PullEvent is a value object: immutable and compared by value.
type PullEvent struct {
	Repo          string `json:"repo"`
	Reference     string `json:"reference"`
	IsManifestGet bool   `json:"isManifestGet"`
	Timestamp     string `json:"timestamp"`
}

// Equal reports whether two PullEvent values are equal.
func (p PullEvent) Equal(other PullEvent) bool {
	return p == other
}
