// Code generated by sysgo; DO NOT EDIT.

package domain

// SinkKind is a value object: immutable and compared by value.
type SinkKind struct {
	Value string `json:"value"`
}

// Equal reports whether two SinkKind values are equal.
func (s SinkKind) Equal(other SinkKind) bool {
	return s == other
}
