// Code generated by MockGen. DO NOT EDIT.
// Source: verify.go
//
// Generated by this command:
//
//	mockgen -source=verify.go -destination=mocks_test.go -package=sign
//

// Package sign is a generated GoMock package.
package sign

import (
	context "context"
	io "io"
	reflect "reflect"

	v1 "github.com/opencontainers/image-spec/specs-go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
	isgomock struct{}
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockSource) Fetch(ctx context.Context, target v1.Descriptor) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, target)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockSourceMockRecorder) Fetch(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockSource)(nil).Fetch), ctx, target)
}

// Referrers mocks base method.
func (m *MockSource) Referrers(ctx context.Context, desc v1.Descriptor, artifactType string, fn func([]v1.Descriptor) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Referrers", ctx, desc, artifactType, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Referrers indicates an expected call of Referrers.
func (mr *MockSourceMockRecorder) Referrers(ctx, desc, artifactType, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Referrers", reflect.TypeOf((*MockSource)(nil).Referrers), ctx, desc, artifactType, fn)
}
