// Code generated by sysgo; DO NOT EDIT.

package domain

// HTTPEndpoint is a value object: immutable and compared by value.
type HTTPEndpoint struct {
	URL string `json:"url"`
}

// Equal reports whether two HTTPEndpoint values are equal.
func (h HTTPEndpoint) Equal(other HTTPEndpoint) bool {
	return h == other
}
