// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/composition/domain"
)

// CaptureDependencyPinInput is the input DTO for the CaptureDependencyPin use case.
type CaptureDependencyPinInput struct {
	Layer domain.Layer `json:"layer"`
}

// CaptureDependencyPinOutput is the output DTO for the CaptureDependencyPin use case.
type CaptureDependencyPinOutput struct {
	Pin domain.PinRecord `json:"pin"`
}

// CaptureDependencyPinUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type CaptureDependencyPinUseCase interface {
	CaptureDependencyPin(input CaptureDependencyPinInput) (CaptureDependencyPinOutput, error)
}
