// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/composition/domain"
)

// ComposeStackInput is the input DTO for the ComposeStack use case.
type ComposeStackInput struct {
	Request domain.ComposeRequest `json:"request"`
}

// ComposeStackOutput is the output DTO for the ComposeStack use case.
type ComposeStackOutput struct {
	Merged domain.MergedSkill `json:"merged"`
}

// ComposeStackUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type ComposeStackUseCase interface {
	ComposeStack(input ComposeStackInput) (ComposeStackOutput, error)
}
