// Code generated by sysgo; DO NOT EDIT.

package in

import (
	"github.com/gaarutyunov/epos/internal/composition/domain"
)

// VerifyPinInput is the input DTO for the VerifyPin use case.
type VerifyPinInput struct {
	Expected domain.PinRecord `json:"expected"`
}

// VerifyPinOutput is the output DTO for the VerifyPin use case.
type VerifyPinOutput struct {
	Ok bool `json:"ok"`
}

// VerifyPinUseCase is a driving (inbound) port: the boundary through which the
// outside world invokes application behavior.
type VerifyPinUseCase interface {
	VerifyPin(input VerifyPinInput) (VerifyPinOutput, error)
}
