// Code generated by sysgo; DO NOT EDIT.

package domain

// ConfigBlob is a value object: immutable and compared by value.
type ConfigBlob struct {
	MediaType MediaType `json:"mediaType"`
	Digest    Digest    `json:"digest"`
	SizeBytes int64     `json:"sizeBytes"`
}

// Equal reports whether two ConfigBlob values are equal.
func (c ConfigBlob) Equal(other ConfigBlob) bool {
	return c == other
}
