// Code generated by sysgo; DO NOT EDIT.

package domain

// ContentLayer is a value object: immutable and compared by value.
type ContentLayer struct {
	MediaType MediaType `json:"mediaType"`
	Digest    Digest    `json:"digest"`
	SizeBytes int64     `json:"sizeBytes"`
}

// Equal reports whether two ContentLayer values are equal.
func (c ContentLayer) Equal(other ContentLayer) bool {
	return c == other
}
