// Code generated by sysgo; DO NOT EDIT.

package domain

// Digest is a value object: immutable and compared by value.
type Digest struct {
	Algo  string `json:"algo"`
	Value string `json:"value"`
}

// Equal reports whether two Digest values are equal.
func (d Digest) Equal(other Digest) bool {
	return d == other
}
