// Code generated by sysgo; DO NOT EDIT.

package domain

// MediaType is a value object: immutable and compared by value.
type MediaType struct {
	Value string `json:"value"`
}

// Equal reports whether two MediaType values are equal.
func (m MediaType) Equal(other MediaType) bool {
	return m == other
}
