// Code generated by sysgo; DO NOT EDIT.

package domain

// OciRef is a value object: immutable and compared by value.
type OciRef struct {
	Registry string `json:"registry"`
	Repo     string `json:"repo"`
	Tag      string `json:"tag"`
}

// Equal reports whether two OciRef values are equal.
func (o OciRef) Equal(other OciRef) bool {
	return o == other
}
