// Code generated by sysgo; DO NOT EDIT.

package domain

// PackagedArtifact is a value object: immutable and compared by value.
type PackagedArtifact struct {
	Ref    OciRef `json:"ref"`
	Digest Digest `json:"digest"`
}

// Equal reports whether two PackagedArtifact values are equal.
func (p PackagedArtifact) Equal(other PackagedArtifact) bool {
	return p == other
}
