// Code generated by sysgo; DO NOT EDIT.

package domain

// PackageRequest is a value object: immutable and compared by value.
type PackageRequest struct {
	SourceDir string `json:"sourceDir"`
}

// Equal reports whether two PackageRequest values are equal.
func (p PackageRequest) Equal(other PackageRequest) bool {
	return p == other
}
