// Code generated by sysgo; DO NOT EDIT.

package domain

// SemVer is a value object: immutable and compared by value.
type SemVer struct {
	Raw   string `json:"raw"`
	Major int64  `json:"major"`
	Minor int64  `json:"minor"`
	Patch int64  `json:"patch"`
	Build string `json:"build"`
}

// Equal reports whether two SemVer values are equal.
func (s SemVer) Equal(other SemVer) bool {
	return s == other
}
