// Code generated by sysgo; DO NOT EDIT.

package domain

// SkillArtifact is an aggregate root. It is the consistency boundary for its
// contained entities and value objects; mutate it only through its methods.
type SkillArtifact struct {
	ID       string        `json:"id"`
	Metadata SkillMetadata `json:"metadata"`
	Config   ConfigBlob    `json:"config"`
	Content  ContentLayer  `json:"content"`
	Files    []SkillFile   `json:"files"`
}
