// Code generated by sysgo; DO NOT EDIT.

package domain

// SkillMetadata is a value object: immutable and compared by value.
type SkillMetadata struct {
	Name        string   `json:"name"`
	Version     SemVer   `json:"version"`
	Description string   `json:"description"`
	Keywords    []string `json:"keywords"`
	Home        string   `json:"home"`
}
