// Code generated by sysgo; DO NOT EDIT.

package domain

// SkillFile is a value object: immutable and compared by value.
type SkillFile struct {
	Path      string `json:"path"`
	IsBinary  bool   `json:"isBinary"`
	SizeBytes int64  `json:"sizeBytes"`
}

// Equal reports whether two SkillFile values are equal.
func (s SkillFile) Equal(other SkillFile) bool {
	return s == other
}
