// Code generated by sysgo; DO NOT EDIT.

package domain

// NewSkillArtifact is a factory that constructs a valid SkillArtifact aggregate.
// Add invariant checks here; return an error when they are violated.
func NewSkillArtifact() (*SkillArtifact, error) {
	return &SkillArtifact{}, nil
}
