// Code generated by sysgo; DO NOT EDIT.

package domain

// ValidationReport is a value object: immutable and compared by value.
type ValidationReport struct {
	Ok       bool     `json:"ok"`
	Messages []string `json:"messages"`
}
