// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	http "net/http"
	reflect "reflect"

	metrics "github.com/gaarutyunov/epos/internal/metrics"
	gomock "go.uber.org/mock/gomock"
)

// Mockrelayer is a mock of relayer interface.
type Mockrelayer struct {
	ctrl     *gomock.Controller
	recorder *MockrelayerMockRecorder
	isgomock struct{}
}

// MockrelayerMockRecorder is the mock recorder for Mockrelayer.
type MockrelayerMockRecorder struct {
	mock *Mockrelayer
}

// NewMockrelayer creates a new mock instance.
func NewMockrelayer(ctrl *gomock.Controller) *Mockrelayer {
	mock := &Mockrelayer{ctrl: ctrl}
	mock.recorder = &MockrelayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrelayer) EXPECT() *MockrelayerMockRecorder {
	return m.recorder
}

// Relay mocks base method.
func (m *Mockrelayer) Relay(w http.ResponseWriter, r *http.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Relay", w, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Relay indicates an expected call of Relay.
func (mr *MockrelayerMockRecorder) Relay(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Relay", reflect.TypeOf((*Mockrelayer)(nil).Relay), w, r)
}

// MockdownloadRecorder is a mock of downloadRecorder interface.
type MockdownloadRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockdownloadRecorderMockRecorder
	isgomock struct{}
}

// MockdownloadRecorderMockRecorder is the mock recorder for MockdownloadRecorder.
type MockdownloadRecorderMockRecorder struct {
	mock *MockdownloadRecorder
}

// NewMockdownloadRecorder creates a new mock instance.
func NewMockdownloadRecorder(ctrl *gomock.Controller) *MockdownloadRecorder {
	mock := &MockdownloadRecorder{ctrl: ctrl}
	mock.recorder = &MockdownloadRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdownloadRecorder) EXPECT() *MockdownloadRecorderMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockdownloadRecorder) Record(ctx context.Context, dl metrics.Download) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", ctx, dl)
}

// Record indicates an expected call of Record.
func (mr *MockdownloadRecorderMockRecorder) Record(ctx, dl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockdownloadRecorder)(nil).Record), ctx, dl)
}
